### ISSUE TITLE
Pixely icon design ideas

### ISSUE THREAD

**Issue by tfuxu** [tfuxu/Halftone#1]
Pixely doesn't currently have an icon to represent itself. I've made a prototype of a symbolic icon to give a general idea how a full icon could look like.

Here's the symbolic:
![pixely-symbolic-256proto](https://github.com/tfuxu/Pixely/assets/73042332/27d76e95-ed96-44cd-ac42-9f07682204d3)

Source SVG: https://github.com/tfuxu/Pixely/assets/73042332/128f7563-db8a-4a36-baba-f93c278f0994
Short description: It's a mish-mash of `image-symbolic`, `decode-symbolic` and `checkerboard-symbolic` icons

**Comment by daudix-UFO** [comment]
As app were renamed to Halftone, now something interesting can be done with the icon :)

**Comment by tfuxu** [comment]
c6d6a4aca54dfd4abfb425945b60571759c50df2
