### ISSUE TITLE
Contrast controls

### ISSUE THREAD

**Issue by hellpe** [tfuxu/Halftone#12]
When I'm creating my dithered images [for my blog](https://write.as/ailepet/), I usually add more contrast (and adjust the brightness accordingly) before applying dithering and see how it turns out. Most of the time, I need to cancel the dithering and re-adjust contrast/brightness before re-applying. So in my usecase, it could be very useful to have such controls directly available in Halftone.

**Comment by tfuxu** [comment]
True, contrast/brightness controls would be very convenient in Halftone, I'll try to implement them soon. Thanks for reporting!
