### ISSUE TITLE
Bayer dither doesn't respect color amount

### ISSUE THREAD

**Issue by daudix-UFO** [tfuxu/Halftone#21]
Noticed that ordered dither uses same color amount no matter how high you set it, comparing with Pixfect (`ditherer.sh`) it looks quite different (same 128 px | 10 colors)

![halftone-bay-bridge](https://github.com/tfuxu/Halftone/assets/77155297/48ce89f9-93a9-4f52-86e7-2682e80a058c)

![bay-bridge-ditherer](https://github.com/tfuxu/Halftone/assets/77155297/4d9a0a62-1175-45eb-b218-ce1709931bef)

**Comment by tfuxu** [comment]
That's because your script is setting levels per color channel, instead of reducing the amount of colors.
In [`ditherer.sh`#L103](https://github.com/daudix-UFO/Pixfect/blob/a82405b6ad2eb74f508a5671a8be7d47f2692a04/ditherer.sh#L103) instead of a comma there should be `-colors` option.

**Comment by daudix-UFO** [comment]
aha, so bug is actually in my script, haha :D
