### ISSUE TITLE
"Open in External Image Viewer" button not working

### ISSUE THREAD

**Issue by daudix-UFO** [tfuxu/Halftone#31]
"Open in External Image Viewer" button not working with [Loupe](https://flathub.org/apps/org.gnome.Loupe) nor the EoG, there are no logs apparently

[Запись экрана от 2023-07-23 15-55-28.webm](https://github.com/tfuxu/Halftone/assets/77155297/edd6cd49-6aaa-4b05-b5d5-30e1fda5c80d)

**Comment by tfuxu** [comment]
Sorry for delay, I was on vacation.
I can't for some reason reproduce that, please send some info about your system.

**Comment by tfuxu** [comment]
Fixed in commit faa0c8fb4ec4fbaef0d4b1988ce577804bcc444c

**Comment by daudix-UFO** [comment]
Thanks a lot!

**Comment by daudix-UFO** [comment]
Tested the fix, there are now this issue

![image](https://github.com/tfuxu/Halftone/assets/77155297/ab1c7289-c576-475a-ae24-d8b19f137617)
