### ISSUE TITLE
No preview on a specific image

### ISSUE THREAD

**Issue by hellpe** [tfuxu/Halftone#34]
Using version 0.3.1 from Flatpak on Fedora Silverblue 38

The attached sample.png file (generated from a color image that I've desaturated using https://maoschanz.github.io/drawing/) does not display any preview when loaded in Halftone (see screenshot). I cannot reproduce this issue with other files from the same folder, so I don't think this is a sandboxing issue

![image](https://github.com/tfuxu/Halftone/assets/1238320/46fc297a-66d4-4cca-8404-33c33b02ed50)
![sample](https://github.com/tfuxu/Halftone/assets/1238320/b3d72254-6f37-4623-bcaa-3298fa0f994d)

**Comment by tfuxu** [comment]
This is pretty weird, as the produced preview is a transparent image, whereas if the culprit was the contrast/brightness control, the image would be white instead. 

I'll try to dig deeper into this on the weekend, thanks for the report :)

**Comment by tfuxu** [comment]
@hellpe This got fixed upstream in `Wand` library
