### ISSUE TITLE
Appropriate color scheme

### ISSUE THREAD

**Issue by bragefuglseth** [tfuxu/Halftone#64]
Halftone currently uses the `FORCE_DARK` color scheme. It would be better to use `PREFER_DARK` here, so the app still becomes light when someone explicitly sets the system-wide color scheme preference to `prefer-light` instead of `default`. It's not currently exposed in GNOME, but might be in the future.

**Comment by tfuxu** [comment]
Fixed in a6be24cde3e1f9e7fc01ad9fa55f1440491c1f97
