### ISSUE TITLE
Less disruptive loading of changes

### ISSUE THREAD

**Issue by bragefuglseth** [tfuxu/Halftone#65]
When a change is made currently, the entire image preview is replaced with a spinner. This feels quite disruptive when done often.

Potential solutions:

- Try making the changes load fast enough for a loading screen to become unnecessary
- Overlay the spinner on top of the current image while the next iteration is loading

**Comment by tfuxu** [comment]
Here's how it would look as a overlay:
[Kooha-2024-02-16-16-55-48.webm](https://github.com/tfuxu/Halftone/assets/73042332/d5d16845-8872-412a-9e83-0af05697d6d0)

**Comment by tfuxu** [comment]
I can make it to trigger after some time. How about after ~3 seconds?

**Comment by bragefuglseth** [comment]
Good idea! Try that.

**Comment by tfuxu** [comment]
@bragefuglseth I've added loading overlay in commit 1a4b996aee3c937027cac6f71552d71512bd4eeb. Let me know if something should be changed
