### ISSUE TITLE
Halftone can't load pictures, doesn't provide error messages

### ISSUE THREAD

**Issue by Cwpute** [tfuxu/Halftone#78]
I tried out Halftone today and after choosing a picture i wanted dithered it kept loading but nothing happened. I tried several different formats and sizes after closing the app each time but none would work.
I found i could try to get a trace from Mint's log system and i did get this:
```
13:13:26 systemd: Started flatpak portal.
13:13:26 systemd: Started flatpak portal.
13:13:26 systemd: Starting flatpak portal...
13:13:24 systemd: Started app-flatpak-io.github.tfuxu.Halftone-3639.scope.
13:13:24 systemd: Failed to start flatpak document portal service.
13:13:24 systemd: xdg-document-portal.service: Failed with result 'exit-code'.
13:13:24 systemd: xdg-document-portal.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
13:13:24 xdg-document-po: error: Failed to load db from '/home/userx/.local/share/flatpak/db/documents': invalid gvdb header
```

I wasn't getting any error messages as well do i didn't know if anything was wrong or if it was simply really slow.

**Comment by tfuxu** [comment]
I think this is an issue with your configuration. Here's an issue on xdg-desktop-portal that describes this exact problem: https://github.com/flatpak/xdg-desktop-portal/issues/728

**Comment by Cwpute** [comment]
Alright, i'll update Linux Mint to v22, as i undirstood it will hopefully fix this issue.
