### ISSUE TITLE
Inifinte loading, no error message

### ISSUE THREAD

**Issue by Cwpute** [tfuxu/Halftone#79]
Following #78 i upgraded to Linux Mint 22 but another error seemingly prevents me from going further.
I can select any picture to dither but it loads indefinitely, still without any error message. The picture i selected was quite small.
This is what i get from the terminal: 
```
flatpak run io.github.tfuxu.Halftone
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers
Traceback (most recent call last):
  File "/app/share/halftone/halftone/views/main_window.py", line 149, in on_image_chooser_response
    self.load_image(input_file)
  File "/app/share/halftone/halftone/views/main_window.py", line 117, in load_image
    self.dither_page.load_preview_image(file)
  File "/app/share/halftone/halftone/views/dither_page.py", line 202, in load_preview_image
    self.input_image_path = file.get_path()
                            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_path'

```
It would be quite useful if Halftone could provide a small message saying it encountered an error, because showing a loading icon gives the wrong impression of an app that is working, even slowly or faultly, but still working, when it is definitely not.

**Comment by tfuxu** [comment]
This is almost the same issue as in #78, just with a different error this time. Try removing `documents` file from `/home/[USERNAME]/.local/share/flatpak/db` and reopen Halftone to check if issue still persists.

Related issue: https://github.com/flatpak/xdg-desktop-portal/issues/627

**Comment by Cwpute** [comment]
I did fix the issue at hand ! Although i had to reload the app twice.
I will now (hopefully) be able to properly test Halftone :)

**Comment by tfuxu** [comment]
Glad to hear that! Also thanks for checking out Halftone
